const express = require("express");
const { rotaUsuario } = require("./controllers/usuario");
const { rotaPontuacao } = require("./controllers/pontuacao");
const { rotaLogin } = require("./controllers/logar");
const server = express();
server.use(express.json());
server.use(rotaUsuario);
server.use(rotaPontuacao);
server.use(rotaLogin);
server.listen(3000, () => console.log("Ro---jjj---"));
